Burger constructor layout
nadine-belanova/react-burger pull request #1
Opened 2023-01-17 15:37 UTC by nadine-belanova

2023-01-17 16:48 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes. 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте `isRequired` там где он пропущен
- Перенесите логику из App в компонент конструктора
- Уберите children из ModalOverlay

Что понравилось:
- Декомпозиция компонентов
- Есть проверка успешности запроса
- Есть отписка от слушателя

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-17 16:48 UTC, andryxxa93 commented on src/App.jsx
> +          console.log(result.data);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-01-17 16:48 UTC, andryxxa93 commented on src/App.jsx
> +  const [sauces, setSauces] = useState([]);
**Необходимо исправить**
Не стоит на уровне `App` фильтровать категории. Компонент App нужен просто для инициализации, здесь всё только необходимое, а конкретные реализации бизнес логики должны быть на уровне компонентов. Достаточно передавать в конструктор все ингредиенты и уже там распределять по категориям.

2023-01-17 16:48 UTC, andryxxa93 commented on src/components/Modal/index.jsx
> +        return () => window.removeEventListener('keydown', close);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-01-17 16:48 UTC, andryxxa93 commented on src/components/Modal/index.jsx
> +Modal.propTypes = {
**Необходимо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2023-01-17 16:48 UTC, andryxxa93 commented on src/components/ModalOverlay/index.jsx
> +    return <div className={styles.overlay} onClick={onClose}>{children}</div>
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`

2023-01-17 16:48 UTC, andryxxa93 commented on src/App.jsx
> +    fetch(INGRIDIENTS_URL)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-01-18 18:33 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-18 18:54 UTC, nadine-belanova commented on src/components/BurgerConstructor/index.jsx
> +    const buns = useMemo(() => ingridients.filter(item => item.type === 'bun'));
Спасибо

2023-01-18 18:56 UTC, merged